CREATE TABLE `enrichment_jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`status` enum('pending','running','paused','completed','failed') NOT NULL DEFAULT 'pending',
	`totalClientes` int NOT NULL,
	`processedClientes` int NOT NULL DEFAULT 0,
	`successClientes` int NOT NULL DEFAULT 0,
	`failedClientes` int NOT NULL DEFAULT 0,
	`currentBatch` int NOT NULL DEFAULT 0,
	`totalBatches` int NOT NULL,
	`batchSize` int NOT NULL DEFAULT 5,
	`checkpointInterval` int NOT NULL DEFAULT 50,
	`startedAt` timestamp,
	`pausedAt` timestamp,
	`completedAt` timestamp,
	`estimatedTimeRemaining` int,
	`lastClienteId` int,
	`errorMessage` text,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()),
	CONSTRAINT `enrichment_jobs_id` PRIMARY KEY(`id`)
);
