CREATE TABLE `enrichment_configs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`openaiApiKey` text,
	`serpapiKey` text,
	`receitawsKey` text,
	`produtosPorMercado` int NOT NULL DEFAULT 3,
	`concorrentesPorMercado` int NOT NULL DEFAULT 5,
	`leadsPorMercado` int NOT NULL DEFAULT 5,
	`batchSize` int NOT NULL DEFAULT 50,
	`checkpointInterval` int NOT NULL DEFAULT 100,
	`enableDeduplication` int NOT NULL DEFAULT 1,
	`enableQualityScore` int NOT NULL DEFAULT 1,
	`enableAutoRetry` int NOT NULL DEFAULT 1,
	`maxRetries` int NOT NULL DEFAULT 2,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()),
	CONSTRAINT `enrichment_configs_id` PRIMARY KEY(`id`),
	CONSTRAINT `enrichment_configs_projectId_unique` UNIQUE(`projectId`)
);
