CREATE TABLE `analytics_dimensoes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`pesquisaId` int,
	`dimensaoTipo` enum('uf','porte','segmentacao','categoria') NOT NULL,
	`dimensaoValor` varchar(100) NOT NULL,
	`totalLeads` int DEFAULT 0,
	`qualidadeMedia` int DEFAULT 0,
	`taxaConversaoSF` int DEFAULT 0,
	`custoMedioLead` int DEFAULT 0,
	`roi` int DEFAULT 0,
	`updatedAt` timestamp DEFAULT (now()),
	`createdAt` timestamp DEFAULT (now()),
	CONSTRAINT `analytics_dimensoes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `analytics_mercados` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`pesquisaId` int,
	`mercadoId` int NOT NULL,
	`periodo` timestamp NOT NULL,
	`totalClientes` int DEFAULT 0,
	`totalConcorrentes` int DEFAULT 0,
	`totalLeadsGerados` int DEFAULT 0,
	`taxaCoberturaMercado` int DEFAULT 0,
	`qualidadeMediaLeads` int DEFAULT 0,
	`leadsAltaQualidade` int DEFAULT 0,
	`leadsMediaQualidade` int DEFAULT 0,
	`leadsBaixaQualidade` int DEFAULT 0,
	`leadsEnriquecidos` int DEFAULT 0,
	`taxaSucessoEnriquecimento` int DEFAULT 0,
	`tempoMedioEnriquecimentoMin` int DEFAULT 0,
	`custoEnriquecimentoTotal` int DEFAULT 0,
	`leadsValidados` int DEFAULT 0,
	`leadsAprovados` int DEFAULT 0,
	`leadsDescartados` int DEFAULT 0,
	`taxaAprovacao` int DEFAULT 0,
	`leadsExportadosSF` int DEFAULT 0,
	`leadsConvertidosSF` int DEFAULT 0,
	`taxaConversaoSF` int DEFAULT 0,
	`horasPesquisa` int DEFAULT 0,
	`custoTotal` int DEFAULT 0,
	`roi` int DEFAULT 0,
	`updatedAt` timestamp DEFAULT (now()),
	`createdAt` timestamp DEFAULT (now()),
	CONSTRAINT `analytics_mercados_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `analytics_pesquisas` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`pesquisaId` int NOT NULL,
	`totalMercadosMapeados` int DEFAULT 0,
	`totalClientesBase` int DEFAULT 0,
	`totalLeadsGerados` int DEFAULT 0,
	`taxaConversaoClienteLead` int DEFAULT 0,
	`qualidadeMediaGeral` int DEFAULT 0,
	`distribuicaoQualidade` text,
	`taxaSucessoEnriquecimento` int DEFAULT 0,
	`tempoTotalEnriquecimentoHoras` int DEFAULT 0,
	`custoTotalEnriquecimento` int DEFAULT 0,
	`leadsExportadosSF` int DEFAULT 0,
	`leadsConvertidosSF` int DEFAULT 0,
	`taxaConversaoSF` int DEFAULT 0,
	`valorPipelineGerado` int DEFAULT 0,
	`custoTotalPesquisa` int DEFAULT 0,
	`valorGerado` int DEFAULT 0,
	`roi` int DEFAULT 0,
	`dataInicio` timestamp,
	`dataConclusao` timestamp,
	`duracaoDias` int DEFAULT 0,
	`updatedAt` timestamp DEFAULT (now()),
	`createdAt` timestamp DEFAULT (now()),
	CONSTRAINT `analytics_pesquisas_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `analytics_timeline` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`data` timestamp NOT NULL,
	`leadsGeradosDia` int DEFAULT 0,
	`leadsEnriquecidosDia` int DEFAULT 0,
	`leadsValidadosDia` int DEFAULT 0,
	`leadsExportadosSFDia` int DEFAULT 0,
	`qualidadeMediaDia` int DEFAULT 0,
	`custoDia` int DEFAULT 0,
	`leadsAcumulados` int DEFAULT 0,
	`custoAcumulado` int DEFAULT 0,
	`valorGeradoAcumulado` int DEFAULT 0,
	`updatedAt` timestamp DEFAULT (now()),
	`createdAt` timestamp DEFAULT (now()),
	CONSTRAINT `analytics_timeline_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `operational_alerts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`alertType` enum('qualidade_baixa','enriquecimento_lento','backlog_validacao','custo_elevado','conversao_sf_baixa') NOT NULL,
	`severity` enum('low','medium','high','critical') NOT NULL DEFAULT 'medium',
	`titulo` varchar(255) NOT NULL,
	`mensagem` text NOT NULL,
	`acaoRecomendada` text,
	`valorAtual` text,
	`valorEsperado` text,
	`isRead` int NOT NULL DEFAULT 0,
	`isDismissed` int NOT NULL DEFAULT 0,
	`createdAt` timestamp DEFAULT (now()),
	`readAt` timestamp,
	`dismissedAt` timestamp,
	CONSTRAINT `operational_alerts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `recommendations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`tipo` enum('mercado','regiao','metodologia','filtro','otimizacao') NOT NULL,
	`prioridade` enum('baixa','media','alta') NOT NULL DEFAULT 'media',
	`titulo` varchar(255) NOT NULL,
	`descricao` text NOT NULL,
	`acao` text NOT NULL,
	`leadsAdicionaisEstimado` int DEFAULT 0,
	`qualidadeEsperada` int DEFAULT 0,
	`custoEstimado` int DEFAULT 0,
	`roiEsperado` int DEFAULT 0,
	`isApplied` int NOT NULL DEFAULT 0,
	`isDismissed` int NOT NULL DEFAULT 0,
	`createdAt` timestamp DEFAULT (now()),
	`appliedAt` timestamp,
	`dismissedAt` timestamp,
	CONSTRAINT `recommendations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `salesforce_sync_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`pesquisaId` int,
	`syncType` enum('manual','automatico') NOT NULL DEFAULT 'manual',
	`totalLeadsExportados` int DEFAULT 0,
	`totalLeadsSucesso` int DEFAULT 0,
	`totalLeadsErro` int DEFAULT 0,
	`status` enum('em_progresso','concluido','erro') NOT NULL DEFAULT 'em_progresso',
	`errorMessage` text,
	`leadIds` text,
	`createdAt` timestamp DEFAULT (now()),
	`completedAt` timestamp,
	CONSTRAINT `salesforce_sync_log_id` PRIMARY KEY(`id`)
);
