"use strict";
// ============================================================================
// DRIZZLE SCHEMA - GERADO AUTOMATICAMENTE A PARTIR DO BANCO REAL
// Data: 2024-12-06
// Fonte: PostgreSQL Supabase (33 tabelas, 100% sincronizado)
// ============================================================================
Object.defineProperty(exports, "__esModule", { value: true });
exports.usuarios_bloqueados = exports.users = exports.user_profiles = exports.system_settings = exports.roles = exports.rate_limits = exports.importacao_erros = exports.ia_usage = exports.ia_config_historico = exports.ia_config = exports.ia_cache = exports.ia_alertas = exports.fato_entidade_produto = exports.fato_entidade_contexto = exports.fato_entidade_competidor = exports.dim_tempo = exports.dim_status_qualificacao = exports.dim_projeto = exports.dim_produto_old_backup = exports.dim_produto_catalogo = exports.dim_produto = exports.dim_pesquisa = exports.dim_mercado = exports.dim_lead = exports.dim_importacao = exports.dim_geografia = exports.dim_entidade = exports.dim_concorrente = exports.dim_canal = exports.data_audit_logs = exports.cidades_brasil = exports.audit_logs = exports.alertas_seguranca = void 0;
const pg_core_1 = require("drizzle-orm/pg-core");
const drizzle_orm_1 = require("drizzle-orm");
// Tabela: alertas_seguranca (7 campos)
exports.alertas_seguranca = (0, pg_core_1.pgTable)('alertas_seguranca', {
    id: (0, pg_core_1.integer)('id').notNull(),
    user_id: (0, pg_core_1.varchar)('user_id', { length: 255 }),
    tipo: (0, pg_core_1.varchar)('tipo', { length: 50 }).notNull(),
    descricao: (0, pg_core_1.text)('descricao').notNull(),
    severidade: (0, pg_core_1.varchar)('severidade', { length: 20 }).notNull(),
    resolvido: (0, pg_core_1.boolean)('resolvido').default(false),
    created_at: (0, pg_core_1.timestamp)('created_at').default((0, drizzle_orm_1.sql) `now()`),
});
// Tabela: audit_logs (13 campos)
exports.audit_logs = (0, pg_core_1.pgTable)('audit_logs', {
    id: (0, pg_core_1.integer)('id').notNull(),
    user_id: (0, pg_core_1.varchar)('user_id', { length: 255 }).notNull(),
    action: (0, pg_core_1.varchar)('action', { length: 100 }).notNull(),
    endpoint: (0, pg_core_1.varchar)('endpoint', { length: 255 }).notNull(),
    metodo: (0, pg_core_1.varchar)('metodo', { length: 10 }).notNull(),
    parametros: (0, pg_core_1.jsonb)('parametros'),
    resultado: (0, pg_core_1.varchar)('resultado', { length: 50 }),
    erro: (0, pg_core_1.text)('erro'),
    ip_address: (0, pg_core_1.varchar)('ip_address', { length: 50 }),
    user_agent: (0, pg_core_1.text)('user_agent'),
    duracao_ms: (0, pg_core_1.integer)('duracao_ms'),
    custo: (0, pg_core_1.numeric)('custo', { precision: 10, scale: 6 }),
    created_at: (0, pg_core_1.timestamp)('created_at').default((0, drizzle_orm_1.sql) `now()`),
});
// Tabela: cidades_brasil (13 campos)
exports.cidades_brasil = (0, pg_core_1.pgTable)('cidades_brasil', {
    id: (0, pg_core_1.integer)('id').notNull(),
    codigo_ibge: (0, pg_core_1.integer)('codigo_ibge').notNull(),
    nome: (0, pg_core_1.varchar)('nome', { length: 255 }).notNull(),
    latitude: (0, pg_core_1.numeric)('latitude', { precision: 10, scale: 8 }).notNull(),
    longitude: (0, pg_core_1.numeric)('longitude', { precision: 11, scale: 8 }).notNull(),
    capital: (0, pg_core_1.boolean)('capital').default(false),
    codigo_uf: (0, pg_core_1.integer)('codigo_uf').notNull(),
    uf: (0, pg_core_1.varchar)('uf', { length: 2 }).notNull(),
    siafi_id: (0, pg_core_1.varchar)('siafi_id', { length: 10 }),
    ddd: (0, pg_core_1.integer)('ddd'),
    fuso_horario: (0, pg_core_1.varchar)('fuso_horario', { length: 50 }),
    created_at: (0, pg_core_1.timestamp)('created_at').default((0, drizzle_orm_1.sql) `CURRENT_TIMESTAMP`),
    updated_at: (0, pg_core_1.timestamp)('updated_at').default((0, drizzle_orm_1.sql) `CURRENT_TIMESTAMP`),
});
// Tabela: data_audit_logs (11 campos)
exports.data_audit_logs = (0, pg_core_1.pgTable)('data_audit_logs', {
    id: (0, pg_core_1.bigint)('id', { mode: 'number' }).notNull(),
    tabela: (0, pg_core_1.varchar)('tabela', { length: 100 }).notNull(),
    operacao: (0, pg_core_1.varchar)('operacao', { length: 10 }).notNull(),
    registro_id: (0, pg_core_1.integer)('registro_id').notNull(),
    dados_anteriores: (0, pg_core_1.jsonb)('dados_anteriores'),
    dados_novos: (0, pg_core_1.jsonb)('dados_novos'),
    campos_alterados: (0, pg_core_1.text)('campos_alterados'),
    usuario_id: (0, pg_core_1.varchar)('usuario_id', { length: 255 }),
    ip_address: (0, pg_core_1.varchar)('ip_address', { length: 45 }),
    user_agent: (0, pg_core_1.text)('user_agent'),
    created_at: (0, pg_core_1.timestamp)('created_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
});
// Tabela: dim_canal (14 campos)
exports.dim_canal = (0, pg_core_1.pgTable)('dim_canal', {
    id: (0, pg_core_1.integer)('id').notNull(),
    codigo: (0, pg_core_1.varchar)('codigo', { length: 50 }).notNull(),
    nome: (0, pg_core_1.varchar)('nome', { length: 100 }).notNull(),
    tipo: (0, pg_core_1.varchar)('tipo', { length: 50 }).notNull(),
    descricao: (0, pg_core_1.text)('descricao'),
    custo_medio: (0, pg_core_1.numeric)('custo_medio', { precision: 12, scale: 2 }),
    taxa_conversao_media: (0, pg_core_1.numeric)('taxa_conversao_media', { precision: 5, scale: 2 }),
    ativo: (0, pg_core_1.boolean)('ativo').default(true),
    created_at: (0, pg_core_1.timestamp)('created_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
    created_by: (0, pg_core_1.varchar)('created_by', { length: 255 }),
    updated_at: (0, pg_core_1.timestamp)('updated_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
    updated_by: (0, pg_core_1.varchar)('updated_by', { length: 255 }),
    deleted_by: (0, pg_core_1.varchar)('deleted_by', { length: 255 }),
    deleted_at: (0, pg_core_1.timestamp)('deleted_at'),
});
// Tabela: dim_concorrente (12 campos)
exports.dim_concorrente = (0, pg_core_1.pgTable)('dim_concorrente', {
    id: (0, pg_core_1.integer)('id').notNull(),
    entidade_id: (0, pg_core_1.integer)('entidade_id').notNull(),
    nome: (0, pg_core_1.varchar)('nome', { length: 255 }).notNull(),
    cnpj: (0, pg_core_1.varchar)('cnpj', { length: 18 }),
    cidade: (0, pg_core_1.varchar)('cidade', { length: 100 }).notNull(),
    uf: (0, pg_core_1.varchar)('uf', { length: 2 }).notNull(),
    produto_principal: (0, pg_core_1.text)('produto_principal'),
    site: (0, pg_core_1.varchar)('site', { length: 500 }),
    porte: (0, pg_core_1.varchar)('porte', { length: 20 }),
    ordem: (0, pg_core_1.integer)('ordem').default(1),
    created_at: (0, pg_core_1.timestamp)('created_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
    created_by: (0, pg_core_1.varchar)('created_by', { length: 255 }).notNull(),
});
// Tabela: dim_entidade (49 campos)
exports.dim_entidade = (0, pg_core_1.pgTable)('dim_entidade', {
    id: (0, pg_core_1.integer)('id').notNull(),
    entidade_hash: (0, pg_core_1.varchar)('entidade_hash', { length: 64 }).notNull(),
    tipo_entidade: (0, pg_core_1.varchar)('tipo_entidade', { length: 20 }).notNull(),
    nome: (0, pg_core_1.varchar)('nome', { length: 255 }).notNull(),
    nome_fantasia: (0, pg_core_1.varchar)('nome_fantasia', { length: 255 }),
    cnpj: (0, pg_core_1.varchar)('cnpj', { length: 18 }),
    email: (0, pg_core_1.varchar)('email', { length: 255 }),
    telefone: (0, pg_core_1.varchar)('telefone', { length: 20 }),
    site: (0, pg_core_1.varchar)('site', { length: 255 }),
    num_filiais: (0, pg_core_1.integer)('num_filiais').default(0),
    num_lojas: (0, pg_core_1.integer)('num_lojas').default(0),
    num_funcionarios: (0, pg_core_1.integer)('num_funcionarios'),
    origem_tipo: (0, pg_core_1.varchar)('origem_tipo', { length: 20 }).notNull(),
    origem_arquivo: (0, pg_core_1.varchar)('origem_arquivo', { length: 255 }),
    origem_processo: (0, pg_core_1.varchar)('origem_processo', { length: 100 }),
    origem_prompt: (0, pg_core_1.text)('origem_prompt'),
    origem_confianca: (0, pg_core_1.integer)('origem_confianca'),
    origem_data: (0, pg_core_1.timestamp)('origem_data').notNull().default((0, drizzle_orm_1.sql) `now()`),
    origem_usuario_id: (0, pg_core_1.integer)('origem_usuario_id'),
    created_at: (0, pg_core_1.timestamp)('created_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
    created_by: (0, pg_core_1.varchar)('created_by', { length: 255 }),
    updated_at: (0, pg_core_1.timestamp)('updated_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
    updated_by: (0, pg_core_1.varchar)('updated_by', { length: 255 }),
    deleted_at: (0, pg_core_1.timestamp)('deleted_at'),
    deleted_by: (0, pg_core_1.varchar)('deleted_by', { length: 255 }),
    importacao_id: (0, pg_core_1.integer)('importacao_id'),
    cnpj_hash: (0, pg_core_1.varchar)('cnpj_hash', { length: 64 }),
    cpf_hash: (0, pg_core_1.varchar)('cpf_hash', { length: 64 }),
    email_hash: (0, pg_core_1.varchar)('email_hash', { length: 64 }),
    telefone_hash: (0, pg_core_1.varchar)('telefone_hash', { length: 64 }),
    cidade: (0, pg_core_1.varchar)('cidade', { length: 100 }),
    uf: (0, pg_core_1.varchar)('uf', { length: 2 }),
    porte: (0, pg_core_1.varchar)('porte', { length: 20 }),
    setor: (0, pg_core_1.varchar)('setor', { length: 100 }),
    produto_principal: (0, pg_core_1.text)('produto_principal'),
    segmentacao_b2b_b2c: (0, pg_core_1.varchar)('segmentacao_b2b_b2c', { length: 10 }),
    score_qualidade: (0, pg_core_1.integer)('score_qualidade'),
    enriquecido_em: (0, pg_core_1.timestamp)('enriquecido_em'),
    enriquecido_por: (0, pg_core_1.varchar)('enriquecido_por', { length: 255 }),
    cache_hit: (0, pg_core_1.boolean)('cache_hit').default(false),
    cache_expires_at: (0, pg_core_1.timestamp)('cache_expires_at'),
    score_qualidade_dados: (0, pg_core_1.integer)('score_qualidade_dados').default(0),
    validacao_cnpj: (0, pg_core_1.boolean)('validacao_cnpj').default(false),
    validacao_email: (0, pg_core_1.boolean)('validacao_email').default(false),
    validacao_telefone: (0, pg_core_1.boolean)('validacao_telefone').default(false),
    campos_faltantes: (0, pg_core_1.text)('campos_faltantes'),
    ultima_validacao: (0, pg_core_1.timestamp)('ultima_validacao'),
    status_qualificacao_id: (0, pg_core_1.integer)('status_qualificacao_id'),
    enriquecido: (0, pg_core_1.boolean)('enriquecido').default(false),
});
// Tabela: dim_geografia (19 campos)
exports.dim_geografia = (0, pg_core_1.pgTable)('dim_geografia', {
    id: (0, pg_core_1.integer)('id').notNull(),
    cidade: (0, pg_core_1.varchar)('cidade', { length: 100 }).notNull(),
    uf: (0, pg_core_1.varchar)('uf', { length: 2 }).notNull(),
    regiao: (0, pg_core_1.varchar)('regiao', { length: 20 }),
    latitude: (0, pg_core_1.numeric)('latitude', { precision: 10, scale: 8 }),
    longitude: (0, pg_core_1.numeric)('longitude', { precision: 11, scale: 8 }),
    codigo_ibge: (0, pg_core_1.varchar)('codigo_ibge', { length: 10 }),
    populacao: (0, pg_core_1.integer)('populacao'),
    pib_per_capita: (0, pg_core_1.numeric)('pib_per_capita', { precision: 12, scale: 2 }),
    created_at: (0, pg_core_1.timestamp)('created_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
    created_by: (0, pg_core_1.varchar)('created_by', { length: 255 }),
    updated_at: (0, pg_core_1.timestamp)('updated_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
    updated_by: (0, pg_core_1.varchar)('updated_by', { length: 255 }),
    pais: (0, pg_core_1.varchar)('pais', { length: 50 }).default('Brasil'),
    macrorregiao: (0, pg_core_1.varchar)('macrorregiao', { length: 50 }),
    mesorregiao: (0, pg_core_1.varchar)('mesorregiao', { length: 100 }),
    microrregiao: (0, pg_core_1.varchar)('microrregiao', { length: 100 }),
    deleted_by: (0, pg_core_1.varchar)('deleted_by', { length: 255 }),
    deleted_at: (0, pg_core_1.timestamp)('deleted_at'),
});
// Tabela: dim_importacao (27 campos)
exports.dim_importacao = (0, pg_core_1.pgTable)('dim_importacao', {
    id: (0, pg_core_1.integer)('id').notNull(),
    projeto_id: (0, pg_core_1.integer)('projeto_id').notNull(),
    pesquisa_id: (0, pg_core_1.integer)('pesquisa_id').notNull(),
    nome_arquivo: (0, pg_core_1.varchar)('nome_arquivo', { length: 255 }).notNull(),
    tipo_arquivo: (0, pg_core_1.varchar)('tipo_arquivo', { length: 10 }).notNull(),
    tamanho_bytes: (0, pg_core_1.bigint)('tamanho_bytes', { mode: 'number' }),
    caminho_s3: (0, pg_core_1.varchar)('caminho_s3', { length: 500 }),
    total_linhas: (0, pg_core_1.integer)('total_linhas').notNull(),
    linhas_processadas: (0, pg_core_1.integer)('linhas_processadas').default(0),
    linhas_sucesso: (0, pg_core_1.integer)('linhas_sucesso').default(0),
    linhas_erro: (0, pg_core_1.integer)('linhas_erro').default(0),
    linhas_duplicadas: (0, pg_core_1.integer)('linhas_duplicadas').default(0),
    linhas_geografia_fuzzy: (0, pg_core_1.integer)('linhas_geografia_fuzzy').default(0),
    status: (0, pg_core_1.varchar)('status', { length: 20 }).notNull().default('pendente'),
    erro_mensagem: (0, pg_core_1.text)('erro_mensagem'),
    progresso_percentual: (0, pg_core_1.integer)('progresso_percentual').default(0),
    mapeamento_colunas: (0, pg_core_1.jsonb)('mapeamento_colunas'),
    opcoes: (0, pg_core_1.jsonb)('opcoes'),
    started_at: (0, pg_core_1.timestamp)('started_at'),
    completed_at: (0, pg_core_1.timestamp)('completed_at'),
    duration_seconds: (0, pg_core_1.integer)('duration_seconds'),
    created_at: (0, pg_core_1.timestamp)('created_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
    created_by: (0, pg_core_1.varchar)('created_by', { length: 255 }).notNull(),
    updated_at: (0, pg_core_1.timestamp)('updated_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
    updated_by: (0, pg_core_1.varchar)('updated_by', { length: 255 }),
    deleted_by: (0, pg_core_1.varchar)('deleted_by', { length: 255 }),
    deleted_at: (0, pg_core_1.timestamp)('deleted_at'),
});
// Tabela: dim_lead (18 campos)
exports.dim_lead = (0, pg_core_1.pgTable)('dim_lead', {
    id: (0, pg_core_1.integer)('id').notNull(),
    entidade_id: (0, pg_core_1.integer)('entidade_id').notNull(),
    nome: (0, pg_core_1.varchar)('nome', { length: 255 }).notNull(),
    cnpj: (0, pg_core_1.varchar)('cnpj', { length: 18 }),
    cidade: (0, pg_core_1.varchar)('cidade', { length: 100 }).notNull(),
    uf: (0, pg_core_1.varchar)('uf', { length: 2 }).notNull(),
    produto_interesse: (0, pg_core_1.text)('produto_interesse'),
    setor: (0, pg_core_1.varchar)('setor', { length: 100 }),
    site: (0, pg_core_1.varchar)('site', { length: 500 }),
    porte: (0, pg_core_1.varchar)('porte', { length: 20 }),
    score_qualificacao: (0, pg_core_1.integer)('score_qualificacao'),
    prioridade: (0, pg_core_1.varchar)('prioridade', { length: 10 }),
    status: (0, pg_core_1.varchar)('status', { length: 20 }).default('novo'),
    ordem: (0, pg_core_1.integer)('ordem').default(1),
    created_at: (0, pg_core_1.timestamp)('created_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
    created_by: (0, pg_core_1.varchar)('created_by', { length: 255 }).notNull(),
    updated_at: (0, pg_core_1.timestamp)('updated_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
    updated_by: (0, pg_core_1.varchar)('updated_by', { length: 255 }),
});
// Tabela: dim_mercado (21 campos)
exports.dim_mercado = (0, pg_core_1.pgTable)('dim_mercado', {
    id: (0, pg_core_1.integer)('id').notNull(),
    entidade_id: (0, pg_core_1.integer)('entidade_id').notNull(),
    nome: (0, pg_core_1.varchar)('nome', { length: 255 }).notNull(),
    categoria: (0, pg_core_1.varchar)('categoria', { length: 50 }),
    segmentacao: (0, pg_core_1.varchar)('segmentacao', { length: 10 }),
    tamanho_mercado: (0, pg_core_1.text)('tamanho_mercado'),
    crescimento_anual: (0, pg_core_1.varchar)('crescimento_anual', { length: 100 }),
    tendencias: (0, pg_core_1.text)('tendencias'),
    principais_players: (0, pg_core_1.text)('principais_players'),
    created_at: (0, pg_core_1.timestamp)('created_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
    created_by: (0, pg_core_1.varchar)('created_by', { length: 255 }).notNull(),
    updated_at: (0, pg_core_1.timestamp)('updated_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
    updated_by: (0, pg_core_1.varchar)('updated_by', { length: 255 }),
    sentimento: (0, pg_core_1.varchar)('sentimento', { length: 50 }),
    score_atratividade: (0, pg_core_1.integer)('score_atratividade'),
    nivel_saturacao: (0, pg_core_1.varchar)('nivel_saturacao', { length: 50 }),
    oportunidades: (0, pg_core_1.text)('oportunidades'),
    riscos: (0, pg_core_1.text)('riscos'),
    recomendacao_estrategica: (0, pg_core_1.text)('recomendacao_estrategica'),
    deleted_at: (0, pg_core_1.timestamp)('deleted_at'),
    deleted_by: (0, pg_core_1.varchar)('deleted_by', { length: 255 }),
});
// Tabela: dim_pesquisa (21 campos)
exports.dim_pesquisa = (0, pg_core_1.pgTable)('dim_pesquisa', {
    id: (0, pg_core_1.integer)('id').notNull(),
    projeto_id: (0, pg_core_1.integer)('projeto_id').notNull(),
    nome: (0, pg_core_1.varchar)('nome', { length: 255 }).notNull(),
    descricao: (0, pg_core_1.text)('descricao'),
    objetivo: (0, pg_core_1.text)('objetivo'),
    status: (0, pg_core_1.varchar)('status', { length: 20 }).notNull().default('pendente'),
    total_entidades: (0, pg_core_1.integer)('total_entidades').default(0),
    entidades_enriquecidas: (0, pg_core_1.integer)('entidades_enriquecidas').default(0),
    entidades_falhadas: (0, pg_core_1.integer)('entidades_falhadas').default(0),
    qualidade_media: (0, pg_core_1.numeric)('qualidade_media', { precision: 5, scale: 2 }),
    started_at: (0, pg_core_1.timestamp)('started_at'),
    started_by: (0, pg_core_1.varchar)('started_by', { length: 255 }),
    completed_at: (0, pg_core_1.timestamp)('completed_at'),
    duration_seconds: (0, pg_core_1.integer)('duration_seconds'),
    error_message: (0, pg_core_1.text)('error_message'),
    created_at: (0, pg_core_1.timestamp)('created_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
    created_by: (0, pg_core_1.varchar)('created_by', { length: 255 }).notNull(),
    updated_at: (0, pg_core_1.timestamp)('updated_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
    updated_by: (0, pg_core_1.varchar)('updated_by', { length: 255 }),
    deleted_at: (0, pg_core_1.timestamp)('deleted_at'),
    deleted_by: (0, pg_core_1.varchar)('deleted_by', { length: 255 }),
});
// Tabela: dim_produto (17 campos)
exports.dim_produto = (0, pg_core_1.pgTable)('dim_produto', {
    id: (0, pg_core_1.integer)('id').notNull(),
    produto_hash: (0, pg_core_1.varchar)('produto_hash', { length: 64 }).notNull(),
    nome: (0, pg_core_1.varchar)('nome', { length: 255 }).notNull(),
    categoria: (0, pg_core_1.varchar)('categoria', { length: 100 }),
    descricao: (0, pg_core_1.text)('descricao'),
    preco_medio: (0, pg_core_1.numeric)('preco_medio', { precision: 12, scale: 2 }),
    unidade: (0, pg_core_1.varchar)('unidade', { length: 20 }),
    ncm: (0, pg_core_1.varchar)('ncm', { length: 10 }),
    enriquecido: (0, pg_core_1.boolean)('enriquecido').default(false),
    enriquecido_em: (0, pg_core_1.timestamp)('enriquecido_em'),
    enriquecido_por: (0, pg_core_1.varchar)('enriquecido_por', { length: 50 }),
    created_at: (0, pg_core_1.timestamp)('created_at').notNull().default((0, drizzle_orm_1.sql) `CURRENT_TIMESTAMP`),
    created_by: (0, pg_core_1.varchar)('created_by', { length: 255 }),
    updated_at: (0, pg_core_1.timestamp)('updated_at').notNull().default((0, drizzle_orm_1.sql) `CURRENT_TIMESTAMP`),
    updated_by: (0, pg_core_1.varchar)('updated_by', { length: 255 }),
    deleted_by: (0, pg_core_1.varchar)('deleted_by', { length: 255 }),
    deleted_at: (0, pg_core_1.timestamp)('deleted_at'),
});
// Tabela: dim_produto_catalogo (21 campos)
exports.dim_produto_catalogo = (0, pg_core_1.pgTable)('dim_produto_catalogo', {
    produto_id: (0, pg_core_1.integer)('produto_id').notNull(),
    nome: (0, pg_core_1.varchar)('nome', { length: 255 }).notNull(),
    sku: (0, pg_core_1.varchar)('sku', { length: 100 }),
    ean: (0, pg_core_1.varchar)('ean', { length: 20 }),
    ncm: (0, pg_core_1.varchar)('ncm', { length: 10 }),
    categoria: (0, pg_core_1.varchar)('categoria', { length: 100 }),
    subcategoria: (0, pg_core_1.varchar)('subcategoria', { length: 100 }),
    preco: (0, pg_core_1.numeric)('preco', { precision: 15, scale: 2 }),
    moeda: (0, pg_core_1.varchar)('moeda', { length: 3 }).default('BRL'),
    unidade: (0, pg_core_1.varchar)('unidade', { length: 50 }),
    descricao: (0, pg_core_1.text)('descricao'),
    ativo: (0, pg_core_1.boolean)('ativo').default(true),
    data_cadastro: (0, pg_core_1.timestamp)('data_cadastro').notNull().default((0, drizzle_orm_1.sql) `now()`),
    data_atualizacao: (0, pg_core_1.timestamp)('data_atualizacao').notNull().default((0, drizzle_orm_1.sql) `now()`),
    criado_por: (0, pg_core_1.varchar)('criado_por', { length: 255 }),
    atualizado_por: (0, pg_core_1.varchar)('atualizado_por', { length: 255 }),
    fonte: (0, pg_core_1.varchar)('fonte', { length: 100 }),
    created_at: (0, pg_core_1.timestamp)('created_at').default((0, drizzle_orm_1.sql) `now()`),
    updated_at: (0, pg_core_1.timestamp)('updated_at').default((0, drizzle_orm_1.sql) `now()`),
    deleted_at: (0, pg_core_1.timestamp)('deleted_at'),
    deleted_by: (0, pg_core_1.varchar)('deleted_by', { length: 255 }),
});
// Tabela: dim_produto_old_backup (14 campos)
exports.dim_produto_old_backup = (0, pg_core_1.pgTable)('dim_produto_old_backup', {
    id: (0, pg_core_1.integer)('id').notNull(),
    entidade_id: (0, pg_core_1.integer)('entidade_id').notNull(),
    nome: (0, pg_core_1.varchar)('nome', { length: 255 }).notNull(),
    descricao: (0, pg_core_1.text)('descricao'),
    categoria: (0, pg_core_1.varchar)('categoria', { length: 100 }),
    ordem: (0, pg_core_1.integer)('ordem').default(1),
    created_at: (0, pg_core_1.timestamp)('created_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
    created_by: (0, pg_core_1.varchar)('created_by', { length: 255 }).notNull(),
    funcionalidades: (0, pg_core_1.text)('funcionalidades'),
    publico_alvo: (0, pg_core_1.varchar)('publico_alvo', { length: 500 }),
    diferenciais: (0, pg_core_1.text)('diferenciais'),
    tecnologias: (0, pg_core_1.varchar)('tecnologias', { length: 500 }),
    precificacao: (0, pg_core_1.varchar)('precificacao', { length: 500 }),
    deleted_at: (0, pg_core_1.timestamp)('deleted_at'),
});
// Tabela: dim_projeto (15 campos)
exports.dim_projeto = (0, pg_core_1.pgTable)('dim_projeto', {
    id: (0, pg_core_1.integer)('id').notNull(),
    codigo: (0, pg_core_1.varchar)('codigo', { length: 50 }),
    nome: (0, pg_core_1.varchar)('nome', { length: 255 }).notNull(),
    descricao: (0, pg_core_1.text)('descricao'),
    status: (0, pg_core_1.varchar)('status', { length: 20 }).notNull().default('ativo'),
    owner_id: (0, pg_core_1.integer)('owner_id').notNull(),
    unidade_negocio: (0, pg_core_1.varchar)('unidade_negocio', { length: 100 }),
    centro_custo: (0, pg_core_1.varchar)('centro_custo', { length: 50 }),
    orcamento_total: (0, pg_core_1.numeric)('orcamento_total', { precision: 15, scale: 2 }),
    created_at: (0, pg_core_1.timestamp)('created_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
    created_by: (0, pg_core_1.varchar)('created_by', { length: 255 }).notNull(),
    updated_at: (0, pg_core_1.timestamp)('updated_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
    updated_by: (0, pg_core_1.varchar)('updated_by', { length: 255 }),
    deleted_at: (0, pg_core_1.timestamp)('deleted_at'),
    deleted_by: (0, pg_core_1.varchar)('deleted_by', { length: 255 }),
});
// Tabela: dim_status_qualificacao (12 campos)
exports.dim_status_qualificacao = (0, pg_core_1.pgTable)('dim_status_qualificacao', {
    id: (0, pg_core_1.integer)('id').notNull(),
    codigo: (0, pg_core_1.varchar)('codigo', { length: 50 }).notNull(),
    nome: (0, pg_core_1.varchar)('nome', { length: 100 }).notNull(),
    descricao: (0, pg_core_1.text)('descricao'),
    cor: (0, pg_core_1.varchar)('cor', { length: 7 }),
    ordem: (0, pg_core_1.integer)('ordem'),
    created_at: (0, pg_core_1.timestamp)('created_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
    created_by: (0, pg_core_1.varchar)('created_by', { length: 255 }),
    updated_at: (0, pg_core_1.timestamp)('updated_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
    updated_by: (0, pg_core_1.varchar)('updated_by', { length: 255 }),
    deleted_by: (0, pg_core_1.varchar)('deleted_by', { length: 255 }),
    deleted_at: (0, pg_core_1.timestamp)('deleted_at'),
});
// Tabela: dim_tempo (17 campos)
exports.dim_tempo = (0, pg_core_1.pgTable)('dim_tempo', {
    id: (0, pg_core_1.integer)('id').notNull(),
    data: (0, pg_core_1.varchar)('data', { length: 255 }).notNull(),
    ano: (0, pg_core_1.integer)('ano').notNull(),
    trimestre: (0, pg_core_1.integer)('trimestre').notNull(),
    mes: (0, pg_core_1.integer)('mes').notNull(),
    semana: (0, pg_core_1.integer)('semana').notNull(),
    dia_mes: (0, pg_core_1.integer)('dia_mes').notNull(),
    dia_ano: (0, pg_core_1.integer)('dia_ano').notNull(),
    dia_semana: (0, pg_core_1.integer)('dia_semana').notNull(),
    nome_mes: (0, pg_core_1.varchar)('nome_mes', { length: 20 }).notNull(),
    nome_mes_curto: (0, pg_core_1.varchar)('nome_mes_curto', { length: 3 }).notNull(),
    nome_dia_semana: (0, pg_core_1.varchar)('nome_dia_semana', { length: 20 }).notNull(),
    nome_dia_semana_curto: (0, pg_core_1.varchar)('nome_dia_semana_curto', { length: 3 }).notNull(),
    eh_feriado: (0, pg_core_1.boolean)('eh_feriado').default(false),
    eh_fim_semana: (0, pg_core_1.boolean)('eh_fim_semana').default(false),
    eh_dia_util: (0, pg_core_1.boolean)('eh_dia_util').default(true),
    created_at: (0, pg_core_1.timestamp)('created_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
});
// Tabela: fato_entidade_competidor (11 campos)
exports.fato_entidade_competidor = (0, pg_core_1.pgTable)('fato_entidade_competidor', {
    id: (0, pg_core_1.integer)('id').notNull(),
    contexto_id: (0, pg_core_1.integer)('contexto_id').notNull(),
    competidor_entidade_id: (0, pg_core_1.integer)('competidor_entidade_id').notNull(),
    nivel_competicao: (0, pg_core_1.varchar)('nivel_competicao', { length: 20 }),
    diferencial: (0, pg_core_1.text)('diferencial'),
    observacoes: (0, pg_core_1.text)('observacoes'),
    created_at: (0, pg_core_1.timestamp)('created_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
    created_by: (0, pg_core_1.varchar)('created_by', { length: 255 }),
    share_of_voice: (0, pg_core_1.numeric)('share_of_voice', { precision: 5, scale: 2 }),
    vantagem_competitiva_score: (0, pg_core_1.integer)('vantagem_competitiva_score'),
    ameaca_nivel: (0, pg_core_1.varchar)('ameaca_nivel', { length: 20 }),
});
// Tabela: fato_entidade_contexto (38 campos)
exports.fato_entidade_contexto = (0, pg_core_1.pgTable)('fato_entidade_contexto', {
    id: (0, pg_core_1.integer)('id').notNull(),
    entidade_id: (0, pg_core_1.integer)('entidade_id').notNull(),
    projeto_id: (0, pg_core_1.integer)('projeto_id').notNull(),
    pesquisa_id: (0, pg_core_1.integer)('pesquisa_id').notNull(),
    geografia_id: (0, pg_core_1.integer)('geografia_id'),
    mercado_id: (0, pg_core_1.integer)('mercado_id'),
    status_qualificacao_id: (0, pg_core_1.integer)('status_qualificacao_id'),
    cnae: (0, pg_core_1.varchar)('cnae', { length: 10 }),
    porte: (0, pg_core_1.varchar)('porte', { length: 20 }),
    faturamento_estimado: (0, pg_core_1.numeric)('faturamento_estimado', { precision: 15, scale: 2 }),
    num_funcionarios: (0, pg_core_1.integer)('num_funcionarios'),
    qualidade_score: (0, pg_core_1.integer)('qualidade_score'),
    qualidade_classificacao: (0, pg_core_1.varchar)('qualidade_classificacao', { length: 10 }),
    observacoes: (0, pg_core_1.text)('observacoes'),
    created_at: (0, pg_core_1.timestamp)('created_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
    created_by: (0, pg_core_1.varchar)('created_by', { length: 255 }),
    updated_at: (0, pg_core_1.timestamp)('updated_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
    updated_by: (0, pg_core_1.varchar)('updated_by', { length: 255 }),
    deleted_at: (0, pg_core_1.timestamp)('deleted_at'),
    deleted_by: (0, pg_core_1.varchar)('deleted_by', { length: 255 }),
    tempo_id: (0, pg_core_1.integer)('tempo_id'),
    data_qualificacao: (0, pg_core_1.varchar)('data_qualificacao', { length: 255 }).notNull().default('CURRENT_DATE'),
    receita_potencial_anual: (0, pg_core_1.numeric)('receita_potencial_anual', { precision: 15, scale: 2 }),
    ticket_medio_estimado: (0, pg_core_1.numeric)('ticket_medio_estimado', { precision: 12, scale: 2 }),
    ltv_estimado: (0, pg_core_1.numeric)('ltv_estimado', { precision: 15, scale: 2 }),
    cac_estimado: (0, pg_core_1.numeric)('cac_estimado', { precision: 12, scale: 2 }),
    score_fit: (0, pg_core_1.integer)('score_fit'),
    probabilidade_conversao: (0, pg_core_1.numeric)('probabilidade_conversao', { precision: 5, scale: 2 }),
    score_priorizacao: (0, pg_core_1.integer)('score_priorizacao'),
    ciclo_venda_estimado_dias: (0, pg_core_1.integer)('ciclo_venda_estimado_dias'),
    segmento_rfm: (0, pg_core_1.varchar)('segmento_rfm', { length: 3 }),
    segmento_abc: (0, pg_core_1.varchar)('segmento_abc', { length: 1 }),
    eh_cliente_ideal: (0, pg_core_1.boolean)('eh_cliente_ideal').default(false),
    convertido_em_cliente: (0, pg_core_1.boolean)('convertido_em_cliente').default(false),
    data_conversao: (0, pg_core_1.varchar)('data_conversao', { length: 255 }),
    justificativa_score: (0, pg_core_1.text)('justificativa_score'),
    recomendacoes: (0, pg_core_1.text)('recomendacoes'),
    canal_id: (0, pg_core_1.integer)('canal_id'),
});
// Tabela: fato_entidade_produto (12 campos)
exports.fato_entidade_produto = (0, pg_core_1.pgTable)('fato_entidade_produto', {
    id: (0, pg_core_1.integer)('id').notNull(),
    contexto_id: (0, pg_core_1.integer)('contexto_id').notNull(),
    produto_id: (0, pg_core_1.integer)('produto_id').notNull(),
    tipo_relacao: (0, pg_core_1.varchar)('tipo_relacao', { length: 50 }),
    volume_estimado: (0, pg_core_1.varchar)('volume_estimado', { length: 100 }),
    observacoes: (0, pg_core_1.text)('observacoes'),
    volume_vendas_estimado: (0, pg_core_1.numeric)('volume_vendas_estimado', { precision: 15, scale: 2 }),
    margem_estimada: (0, pg_core_1.numeric)('margem_estimada', { precision: 5, scale: 2 }),
    penetracao_mercado: (0, pg_core_1.numeric)('penetracao_mercado', { precision: 5, scale: 2 }),
    eh_produto_principal: (0, pg_core_1.boolean)('eh_produto_principal').default(false),
    created_at: (0, pg_core_1.timestamp)('created_at').notNull().default((0, drizzle_orm_1.sql) `CURRENT_TIMESTAMP`),
    created_by: (0, pg_core_1.varchar)('created_by', { length: 255 }),
});
// Tabela: ia_alertas (9 campos)
exports.ia_alertas = (0, pg_core_1.pgTable)('ia_alertas', {
    id: (0, pg_core_1.integer)('id').notNull(),
    tipo: (0, pg_core_1.varchar)('tipo', { length: 50 }).notNull(),
    percentual: (0, pg_core_1.integer)('percentual').notNull(),
    mensagem: (0, pg_core_1.text)('mensagem').notNull(),
    custo_atual: (0, pg_core_1.numeric)('custo_atual', { precision: 10, scale: 6 }).notNull(),
    budget_total: (0, pg_core_1.numeric)('budget_total', { precision: 10, scale: 2 }).notNull(),
    enviado: (0, pg_core_1.boolean)('enviado').default(false),
    enviado_em: (0, pg_core_1.timestamp)('enviado_em'),
    created_at: (0, pg_core_1.timestamp)('created_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
});
// Tabela: ia_cache (8 campos)
exports.ia_cache = (0, pg_core_1.pgTable)('ia_cache', {
    id: (0, pg_core_1.integer)('id').notNull(),
    cache_key: (0, pg_core_1.varchar)('cache_key', { length: 255 }).notNull(),
    tipo: (0, pg_core_1.varchar)('tipo', { length: 50 }).notNull(),
    dados: (0, pg_core_1.jsonb)('dados').notNull(),
    created_at: (0, pg_core_1.timestamp)('created_at').default((0, drizzle_orm_1.sql) `now()`),
    expires_at: (0, pg_core_1.timestamp)('expires_at').notNull(),
    hits: (0, pg_core_1.integer)('hits').default(0),
    last_hit_at: (0, pg_core_1.timestamp)('last_hit_at'),
});
// Tabela: ia_config (7 campos)
exports.ia_config = (0, pg_core_1.pgTable)('ia_config', {
    id: (0, pg_core_1.integer)('id').notNull(),
    plataforma: (0, pg_core_1.varchar)('plataforma', { length: 50 }).notNull().default('openai'),
    modelo: (0, pg_core_1.varchar)('modelo', { length: 100 }).notNull().default('gpt-4o-mini'),
    budget_mensal: (0, pg_core_1.numeric)('budget_mensal', { precision: 10, scale: 2 }).default('150.00'),
    ativo: (0, pg_core_1.boolean)('ativo').default(true),
    created_at: (0, pg_core_1.timestamp)('created_at').default((0, drizzle_orm_1.sql) `now()`),
    updated_at: (0, pg_core_1.timestamp)('updated_at').default((0, drizzle_orm_1.sql) `now()`),
});
// Tabela: ia_config_historico (7 campos)
exports.ia_config_historico = (0, pg_core_1.pgTable)('ia_config_historico', {
    id: (0, pg_core_1.integer)('id').notNull(),
    plataforma: (0, pg_core_1.varchar)('plataforma', { length: 50 }).notNull(),
    modelo: (0, pg_core_1.varchar)('modelo', { length: 100 }).notNull(),
    budget_mensal: (0, pg_core_1.numeric)('budget_mensal', { precision: 10, scale: 2 }).notNull(),
    alterado_por: (0, pg_core_1.varchar)('alterado_por', { length: 255 }).notNull(),
    alterado_em: (0, pg_core_1.timestamp)('alterado_em').notNull().default((0, drizzle_orm_1.sql) `now()`),
    motivo: (0, pg_core_1.text)('motivo'),
});
// Tabela: ia_usage (15 campos)
exports.ia_usage = (0, pg_core_1.pgTable)('ia_usage', {
    id: (0, pg_core_1.integer)('id').notNull(),
    user_id: (0, pg_core_1.varchar)('user_id', { length: 255 }).notNull(),
    processo: (0, pg_core_1.varchar)('processo', { length: 100 }).notNull(),
    plataforma: (0, pg_core_1.varchar)('plataforma', { length: 50 }).notNull(),
    modelo: (0, pg_core_1.varchar)('modelo', { length: 100 }).notNull(),
    input_tokens: (0, pg_core_1.integer)('input_tokens').notNull(),
    output_tokens: (0, pg_core_1.integer)('output_tokens').notNull(),
    total_tokens: (0, pg_core_1.integer)('total_tokens').notNull(),
    custo: (0, pg_core_1.numeric)('custo', { precision: 10, scale: 6 }).notNull(),
    duracao_ms: (0, pg_core_1.integer)('duracao_ms').notNull(),
    entidade_id: (0, pg_core_1.integer)('entidade_id'),
    projeto_id: (0, pg_core_1.integer)('projeto_id'),
    sucesso: (0, pg_core_1.boolean)('sucesso').default(true),
    erro: (0, pg_core_1.text)('erro'),
    created_at: (0, pg_core_1.timestamp)('created_at').default((0, drizzle_orm_1.sql) `now()`),
});
// Tabela: importacao_erros (9 campos)
exports.importacao_erros = (0, pg_core_1.pgTable)('importacao_erros', {
    id: (0, pg_core_1.integer)('id').notNull(),
    importacao_id: (0, pg_core_1.integer)('importacao_id').notNull(),
    linha_numero: (0, pg_core_1.integer)('linha_numero').notNull(),
    linha_dados: (0, pg_core_1.jsonb)('linha_dados').notNull(),
    campo_erro: (0, pg_core_1.varchar)('campo_erro', { length: 100 }),
    tipo_erro: (0, pg_core_1.varchar)('tipo_erro', { length: 50 }).notNull(),
    mensagem_erro: (0, pg_core_1.text)('mensagem_erro').notNull(),
    sugestao_correcao: (0, pg_core_1.jsonb)('sugestao_correcao'),
    created_at: (0, pg_core_1.timestamp)('created_at').notNull().default((0, drizzle_orm_1.sql) `now()`),
});
// Tabela: rate_limits (7 campos)
exports.rate_limits = (0, pg_core_1.pgTable)('rate_limits', {
    id: (0, pg_core_1.integer)('id').notNull(),
    user_id: (0, pg_core_1.varchar)('user_id', { length: 255 }).notNull(),
    endpoint: (0, pg_core_1.varchar)('endpoint', { length: 255 }).notNull(),
    chamadas: (0, pg_core_1.integer)('chamadas').default(0),
    janela_inicio: (0, pg_core_1.timestamp)('janela_inicio').default((0, drizzle_orm_1.sql) `now()`),
    bloqueado_ate: (0, pg_core_1.timestamp)('bloqueado_ate'),
    created_at: (0, pg_core_1.timestamp)('created_at').default((0, drizzle_orm_1.sql) `now()`),
});
// Tabela: roles (4 campos)
exports.roles = (0, pg_core_1.pgTable)('roles', {
    id: (0, pg_core_1.integer)('id').notNull(),
    nome: (0, pg_core_1.varchar)('nome', { length: 50 }).notNull(),
    descricao: (0, pg_core_1.text)('descricao'),
    created_at: (0, pg_core_1.timestamp)('created_at').default((0, drizzle_orm_1.sql) `now()`),
});
// Tabela: system_settings (6 campos)
exports.system_settings = (0, pg_core_1.pgTable)('system_settings', {
    id: (0, pg_core_1.integer)('id').notNull(),
    settingKey: (0, pg_core_1.varchar)('settingKey', { length: 100 }).notNull(),
    settingValue: (0, pg_core_1.text)('settingValue'),
    description: (0, pg_core_1.text)('description'),
    createdAt: (0, pg_core_1.timestamp)('createdAt').default((0, drizzle_orm_1.sql) `now()`),
    updatedAt: (0, pg_core_1.timestamp)('updatedAt').default((0, drizzle_orm_1.sql) `now()`),
});
// Tabela: user_profiles (8 campos)
exports.user_profiles = (0, pg_core_1.pgTable)('user_profiles', {
    id: (0, pg_core_1.varchar)('id', { length: 255 }).notNull(),
    nome: (0, pg_core_1.varchar)('nome', { length: 255 }).notNull(),
    email: (0, pg_core_1.varchar)('email', { length: 255 }).notNull(),
    senha_hash: (0, pg_core_1.text)('senha_hash').notNull(),
    role_id: (0, pg_core_1.integer)('role_id').notNull().default(4),
    ativo: (0, pg_core_1.boolean)('ativo').default(true),
    ultimo_acesso: (0, pg_core_1.timestamp)('ultimo_acesso'),
    created_at: (0, pg_core_1.timestamp)('created_at').default((0, drizzle_orm_1.sql) `now()`),
});
// Tabela: users (9 campos)
exports.users = (0, pg_core_1.pgTable)('users', {
    id: (0, pg_core_1.varchar)('id', { length: 64 }).notNull(),
    name: (0, pg_core_1.text)('name'),
    email: (0, pg_core_1.varchar)('email', { length: 320 }),
    login_method: (0, pg_core_1.varchar)('login_method', { length: 64 }),
    role: (0, pg_core_1.varchar)('role', { length: 50 }).notNull().default('user'),
    created_at: (0, pg_core_1.timestamp)('created_at').default((0, drizzle_orm_1.sql) `now()`),
    last_signed_in: (0, pg_core_1.timestamp)('last_signed_in').default((0, drizzle_orm_1.sql) `now()`),
    ultimo_acesso: (0, pg_core_1.timestamp)('ultimo_acesso'),
    total_acessos: (0, pg_core_1.integer)('total_acessos').default(0),
});
// Tabela: usuarios_bloqueados (6 campos)
exports.usuarios_bloqueados = (0, pg_core_1.pgTable)('usuarios_bloqueados', {
    id: (0, pg_core_1.integer)('id').notNull(),
    user_id: (0, pg_core_1.varchar)('user_id', { length: 255 }).notNull(),
    motivo: (0, pg_core_1.text)('motivo').notNull(),
    bloqueado_em: (0, pg_core_1.timestamp)('bloqueado_em').default((0, drizzle_orm_1.sql) `now()`),
    bloqueado_ate: (0, pg_core_1.timestamp)('bloqueado_ate').notNull(),
    bloqueado_por: (0, pg_core_1.varchar)('bloqueado_por', { length: 255 }),
});
// ============================================================================
// FIM DO SCHEMA - 33 TABELAS
// ============================================================================
